## clk
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

## switch
set_property PACKAGE_PIN P5 [get_ports in_A3]
set_property IOSTANDARD LVCMOS33 [get_ports in_A3]
set_property PACKAGE_PIN P4 [get_ports in_A2]
set_property IOSTANDARD LVCMOS33 [get_ports in_A2]
set_property PACKAGE_PIN P3 [get_ports in_A1]
set_property IOSTANDARD LVCMOS33 [get_ports in_A1]
set_property PACKAGE_PIN P2 [get_ports in_A0]
set_property IOSTANDARD LVCMOS33 [get_ports in_A0]
set_property PACKAGE_PIN R2 [get_ports in_B3]
set_property IOSTANDARD LVCMOS33 [get_ports in_B3]
set_property PACKAGE_PIN M4 [get_ports in_B2]
set_property IOSTANDARD LVCMOS33 [get_ports in_B2]
set_property PACKAGE_PIN N4 [get_ports in_B1]
set_property IOSTANDARD LVCMOS33 [get_ports in_B1]
set_property PACKAGE_PIN R1 [get_ports in_B0]
set_property IOSTANDARD LVCMOS33 [get_ports in_B0]

##smg位码
set_property PACKAGE_PIN G2 [get_ports an[7]]
set_property IOSTANDARD LVCMOS33 [get_ports an[7]]
set_property PACKAGE_PIN C2 [get_ports an[6]]
set_property IOSTANDARD LVCMOS33 [get_ports an[6]]
set_property PACKAGE_PIN C1 [get_ports an[5]]
set_property IOSTANDARD LVCMOS33 [get_ports an[5]]
set_property PACKAGE_PIN H1 [get_ports an[4]]
set_property IOSTANDARD LVCMOS33 [get_ports an[4]]
set_property PACKAGE_PIN G1 [get_ports an[3]]
set_property IOSTANDARD LVCMOS33 [get_ports an[3]]
set_property PACKAGE_PIN F1 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[2]]
set_property PACKAGE_PIN E1 [get_ports an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports an[1]]
set_property PACKAGE_PIN G6 [get_ports an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports an[0]]

## 段码
set_property PACKAGE_PIN B4 [get_ports {seg0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[0]}]

# 段码2
set_property PACKAGE_PIN D4 [get_ports {seg1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[0]}]
